DATA_DIR: '../dataset'
PP_METHOD: 'norm1'
PRM_ON: True
MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: DSN.dsn_body
  FASTER_RCNN: True
  MASK_ON: False
  LOAD_IMAGENET_PRETRAINED_WEIGHTS: False
  NUM_CLASSES: 2
  BBOX_REG_WEIGHTS: (10., 10., 10., 5., 5., 5.)
  RPN_ONLY: False
RESNETS:
  IMAGENET_PRETRAINED_WEIGHTS: ''
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.01
  GAMMA: 0.5
  MAX_ITER: 9000 # 12000
  STEPS: [0, 3000, 6000, 9000]
FPN:
  FPN_ON: False
  MULTILEVEL_ROIS: False
  MULTILEVEL_RPN: False
RPN:
  SIZES: (10, 12, 14, 16, 18, 20, 22, 24, 28, 30, 34, 36, 38, 40) #(8, 9, 10, 11, 12, 14, 15, 16, 18, 20, 24, 26, 28, 30, 34)
  STRIDE: 4
  ASPECT_RATIOS: [[1.0, 1.0],]
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.roi_2mlp_head
  # MLP_HEAD_DIM: 512 #1024
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
MRCNN:
  ANNO_TYPE: 'spot'
  ROI_MASK_HEAD: mask_rcnn_heads.mask_rcnn_fcn_head_v1up4convs
  RESOLUTION: 14
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  DILATION: 1  # default 2
  CONV_INIT: MSRAFill  # default: GaussianFill
  CLS_SPECIFIC_MASK: False
  ROI_XFORM_SAMPLING_RATIO: 2
TRAIN:
  # IMS_PER_BATCH: 1
  NEED_CROP: True
  USE_FLIPPED: False
  ASPECT_GROUPING: False
  RPN_BATCH_SIZE_PER_IM: 128
  BATCH_SIZE_PER_IM: 128
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
  IN_SIZE: (64, 256, 256)
  RPN_POSITIVE_OVERLAP: 0.4 #default: 0.7
  RPN_NEGATIVE_OVERLAP: 0.2 #default: 0.3
  MAX_SIZE: 256
  FG_THRESH: 0.4 #for fast rcnn head default: 0.5
  BG_THRESH_HI: 0.4 #for fast rcnn head default: 0.5
  SNAPSHOT_ITERS: 3000
  RADIUS_EXP_RATIO: 0.2
TEST:
  NMS: 0.23
  RPN_NMS_THRESH: 0.23
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
  RPN_POST_NMS_TOP_N: 1000
  DETECTIONS_PER_IM: 300
  IN_SIZE: (64, 160, 160)
  SCORE_THRESH: 0.0 # previous 0.05, 0.0 in order to keep more det results for PRM mode
